site_name: My Docs

theme:
  name: 'material'

nav:
  - Home: index.md
  - Dev_documents:
      - Dev_documents/about_git/git.md
      - Dev_documents/request_process/网络请求流程.md
      - Dev_documents/prac/prac.md