site_name: My Docs

theme:
  name: 'material'

nav:
  - Home: index.md
  - Dev_documents:
      - Dev_documents/about_git/git.md
      - Dev_documents/request_process/网络请求流程.md
      - Dev_documents/prac/prac.md
      - Dev_documents/HTML/reference.md
      - Dev_documents/html_doc/HTML手册.md
      - Dev_documents/css_doc/CSS手册.md
      - Dev_documents/css_doc_plus/CSS_advanced.md
      - Dev_documents/pycharm_ad/pc_help.md
      - Dev_documents/oppProgramming/opp.md
      - Dev_documents/java/meetJava.md
  - Django:
      - Django/hello.md
      - Django/message/message.md
      - Django/requestObj/restframeworkRequestObj.md
      - Django/restframework_authentication/restframework_authentication.md
      - Django/restframework_permission/restframework_permission.md
      - Django/restframeworkThrottle/restframeworkThrottle.md
#      - Django/drf/day14drf.md

  - project:
      - project/tables/tables.md